services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    depends_on:
      - postgres
    environment:
      - PHP_IDE_CONFIG=serverName=MasterFinora

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile.postgres
    environment:
      - POSTGRES_DB=MasterFinora
      - POSTGRES_USER=emyr
      - POSTGRES_PASSWORD=obho
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

volumes:
  postgres_data: